services:
    db:
        image: mariadb:11
        container_name: moodle_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MOODLE_DB_NAME:-moodledb}"
            MYSQL_USER: "${MOODLE_DB_USER:-moodledb}"
            MYSQL_PASSWORD: "${MOODLE_DB_PASS}"
        volumes:
            - db_data:/var/lib/mysql
            - ./config/mariadb.conf:/etc/mysql/conf.d/moodle.cnf:ro
        networks:
            - moodle_net
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s
    jobe:
        image: trampgeek/jobeinabox:latest
        container_name: moodle_jobe
        restart: always
        ports:
            - "8080:9063"
        environment:
            - TZ=UTC
        deploy:
            resources:
                limits:
                    cpus: 2.0
                    memory: 4G
    webmin:
        container_name: webmin
        image: longlivethepenguin/webmin:20250819
        hostname: moodle_webmin
        ports:
            - "10000:10000"
        volumes:
            - webmin_data:/etc/webmin
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - moodle_net
        restart: unless-stopped

    moodle:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PHP_VERSION: "8.3"
                MOODLE_BRANCH: "MOODLE_502_STABLE"
        container_name: moodle_app
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "${MOODLE_HTTP_PORT:-80}:80"
        environment:
            MOODLE_DB_HOST: db
            MOODLE_DB_PORT: "3306"
            MOODLE_DB_TYPE: mariadb
            MOODLE_DB_NAME: "${MOODLE_DB_NAME:-moodledb}"
            MOODLE_DB_USER: "${MOODLE_DB_USER:-moodle}"
            MOODLE_DB_PASS: "${MOODLE_DB_PASS}"
            MOODLE_WWWROOT: "${MOODLE_WWWROOT:-http://localhost}"
            MOODLE_SITE_FULLNAME: "${MOODLE_SITE_FULLNAME:-My Moodle Site}"
            MOODLE_SITE_SHORTNAME: "${MOODLE_SITE_SHORTNAME:-moodle}"
            MOODLE_ADMIN_USER: "${MOODLE_ADMIN_USER:-admin}"
            MOODLE_ADMIN_PASS: "${MOODLE_ADMIN_PASS}"
            MOODLE_ADMIN_EMAIL: "${MOODLE_ADMIN_EMAIL:-admin@example.com}"
            MOODLE_DATAROOT: /var/moodledata
            JOBE_HOST: jobe
            JOBE_PORT: "9063"
        volumes:
            - moodle_data:/var/moodledata
        networks:
            - moodle_net

volumes:
    db_data:
        driver: local
    moodle_data:
        driver: local
    webmin_data:
        name: "webmin_data"
        driver: local

networks:
    moodle_net:
        driver: bridge
