#!/usr/bin/env bash
set -euo pipefail

log()  { echo "[entrypoint] $*"; }
die()  { echo "[entrypoint] ERROR: $*" >&2; exit 1; }
php_cli() { gosu www-data php /var/www/html/moodle/admin/cli/"$@"; }

: "${MOODLE_DB_HOST:?Need MOODLE_DB_HOST}"
: "${MOODLE_DB_NAME:?Need MOODLE_DB_NAME}"
: "${MOODLE_DB_USER:?Need MOODLE_DB_USER}"
: "${MOODLE_DB_PASS:?Need MOODLE_DB_PASS}"
: "${MOODLE_WWWROOT:?Need MOODLE_WWWROOT}"
: "${MOODLE_ADMIN_USER:?Need MOODLE_ADMIN_USER}"
: "${MOODLE_ADMIN_PASS:?Need MOODLE_ADMIN_PASS}"
: "${MOODLE_ADMIN_EMAIL:?Need MOODLE_ADMIN_EMAIL}"

MOODLE_DB_PORT="${MOODLE_DB_PORT:-3306}"
MOODLE_DB_TYPE="${MOODLE_DB_TYPE:-mariadb}"   # or 'mysqli'
MOODLE_DATAROOT="${MOODLE_DATAROOT:-/var/moodledata}"
MOODLE_SITE_FULLNAME="${MOODLE_SITE_FULLNAME:-Moodle LMS}"
MOODLE_SITE_SHORTNAME="${MOODLE_SITE_SHORTNAME:-moodle}"

CONFIG_PHP=/var/www/html/moodle/config.php

log "Waiting for database at ${MOODLE_DB_HOST}:${MOODLE_DB_PORT} …"
max_tries=30
count=0
until php -r "
    \$c = @new mysqli('${MOODLE_DB_HOST}', '${MOODLE_DB_USER}', '${MOODLE_DB_PASS}', '', ${MOODLE_DB_PORT});
    exit(\$c->connect_errno ? 1 : 0);
" 2>/dev/null; do
    count=$((count + 1))
    [ $count -ge $max_tries ] && die "Database not reachable after ${max_tries} attempts."
    log "  … attempt ${count}/${max_tries}, retrying in 3 s"
    sleep 3
done
log "Database is reachable."

if [[ ! -f "$CONFIG_PHP" ]] || [[ "${MOODLE_FORCE_CONFIG:-false}" == "true" ]]; then
    log "Writing config.php …"
    cat > "$CONFIG_PHP" <<PHP
<?php  // Moodle configuration file – generated by container entrypoint
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '${MOODLE_DB_TYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DB_HOST}';
\$CFG->dbname    = '${MOODLE_DB_NAME}';
\$CFG->dbuser    = '${MOODLE_DB_USER}';
\$CFG->dbpass    = '${MOODLE_DB_PASS}';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = [
    'dbport'    => ${MOODLE_DB_PORT},
    'dbcollation' => 'utf8mb4_unicode_ci',
];

\$CFG->wwwroot   = '${MOODLE_WWWROOT}';
\$CFG->dataroot  = '${MOODLE_DATAROOT}';
\$CFG->admin     = 'admin';

\$CFG->directorypermissions = 02777;

// Performance
\$CFG->cachetype   = 'file';
\$CFG->sessioncookiepath = '/';

require_once(__DIR__ . '/lib/setup.php');
PHP
    chown www-data:www-data "$CONFIG_PHP"
    chmod 640 "$CONFIG_PHP"
    log "config.php written."
fi

DB_INSTALLED=$(php -r "
    \$c = new mysqli('${MOODLE_DB_HOST}', '${MOODLE_DB_USER}', '${MOODLE_DB_PASS}', '${MOODLE_DB_NAME}', ${MOODLE_DB_PORT});
    \$r = \$c->query(\"SHOW TABLES LIKE 'mdl_config'\");
    echo (\$r && \$r->num_rows > 0) ? 'yes' : 'no';
" 2>/dev/null || echo "no")

if [[ "$DB_INSTALLED" == "no" ]]; then
    log "Fresh install – running Moodle CLI installer …"
    php_cli install.php \
        --lang=en \
        --wwwroot="${MOODLE_WWWROOT}" \
        --dataroot="${MOODLE_DATAROOT}" \
        --dbtype="${MOODLE_DB_TYPE}" \
        --dbhost="${MOODLE_DB_HOST}" \
        --dbname="${MOODLE_DB_NAME}" \
        --dbuser="${MOODLE_DB_USER}" \
        --dbpass="${MOODLE_DB_PASS}" \
        --dbport="${MOODLE_DB_PORT}" \
        --prefix=mdl_ \
        --fullname="${MOODLE_SITE_FULLNAME}" \
        --shortname="${MOODLE_SITE_SHORTNAME}" \
        --adminuser="${MOODLE_ADMIN_USER}" \
        --adminpass="${MOODLE_ADMIN_PASS}" \
        --adminemail="${MOODLE_ADMIN_EMAIL}" \
        --non-interactive \
        --agree-license
    log "Installation complete."
else
    log "Existing installation detected, running upgrade check …"
    php_cli upgrade.php --non-interactive || true
    log "Upgrade check done."
fi

log "Starting cron …"
service cron start

log "Starting Apache …"
exec apache2ctl -D FOREGROUND
